Added emoji support for Trump tweets
BikiniBottomDiscord/fullyautomatednutcracker pull request #38
Opened 2022-01-23 16:21 UTC by Bezbakri

Ignore my bumbling second commit
Also, if you don't have pilmoji, the library, installed, do
`pip install pilmoji`
otherwise, the code won't work

2022-01-24 00:59 UTC, dovedevic commented
Will need to wait for FAN to be upgraded to `nextcord` as it is currently running on py36 and this package requires py38. When the `nextcord` update comes, I'll be upgrading to py310.

2022-06-08 08:05 UTC, Bezbakri commented
Hello dove, the emoji thingy was removed, so no need for an update. Also, added the funny morbius filter.

2022-06-09 00:24 UTC, dovedevic commented
Just use the apply mask method thats already present so we can do resizing and gif support :)

2022-06-09 00:25 UTC, dovedevic requested changes

2022-06-09 00:25 UTC, dovedevic commented on src/fullyautomatednutcracker/cogs/filters.py
> +        await self.save_img_and_send(arguments, ctx.author, ctx.channel, morb_img, file_name="morbius", things_to_close=(img, morb_img, morb_mask))
Just replace all this to

```python
await self.apply_mask(ctx, "morbius.png")
```

2022-06-09 06:04 UTC, Bezbakri commented on src/fullyautomatednutcracker/cogs/filters.py
> +        await self.save_img_and_send(arguments, ctx.author, ctx.channel, morb_img, file_name="morbius", things_to_close=(img, morb_img, morb_mask))
Done. Should be fine now.

2022-06-09 06:08 UTC, dovedevic approved these changes

2022-06-09 06:09 UTC, merged